### ISSUE TITLE
Implement middleware adding toolbar

### ISSUE THREAD

**Issue by samdark** [yiisoft/yii-debug-viewer#1]
A middleware that displays a summary toolbar for current request. Reference is available in Yii 2: https://github.com/yiisoft/yii2-debug/blob/master/src/assets/js/toolbar.js

![debug window](https://user-images.githubusercontent.com/47294/120438359-f3041900-c389-11eb-9b94-5f8dfabf6ec8.jpg)

**Comment by xepozz** [comment]
I just thought that it would be nice to have a section with processed middlewares.

**Comment by samdark** [comment]
Yes. That's a good idea for a panel.
