### ISSUE TITLE
Assets are shown in routes

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-debug-viewer#20]
![image](https://user-images.githubusercontent.com/6815714/152692059-c4503bcb-e594-4806-b485-34e80c18f473.png)

Something bad was happened. Assets are shown is routes in debugger.

**Comment by xepozz** [comment]
Standalone debugger has it own assets. Why have it use another assets?

**Comment by rustamwin** [comment]
We have two ways to add a toolbar right now:
1. Via ToolbarMiddleware. It can be used if the viewer is installed in application.
2. Like in the screenshot below. It can be used if the viewer is installed as standalone app.
![image](https://user-images.githubusercontent.com/16498265/153043315-075d5026-abda-4370-9fd5-b91db6cfce1c.png)

**Comment by samdark** [comment]
I think it is a good idea to allow excluding info about debug toolbar own assets/routes/logs/whatever.
