### ISSUE TITLE
Reorganize routes

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-debug-viewer#22]
AFAIK now route to the debug panel is `/debug/viewer` and `/debug` just works as api.
I suggest to restructure these routes:
* `/debug` - panel
* `/debug/api` - api. It can be conflict with panel routes when we do routes to selected panel for example as `/debug/logger`. Then we cannot add panel with name `api`. But we can make a little workaround `/debug/panel/logger`.

**Comment by samdark** [comment]
Agree that suggested URLs look better. @rustamwin is it possible to achieve?
