### ISSUE TITLE
Show validator results

### ISSUE THREAD

**Issue by xepozz** [yiisoft/yii-debug-viewer#37]
With https://github.com/yiisoft/yii-debug/pull/132 `yii-debug` starts collecting validation errors. 
Now we can show it in the viewer.

**Comment by Sergiayn** [comment]
I want to do it

**Comment by xepozz** [comment]
Any additional info needed?

**Comment by Sergiayn** [comment]
Not needed yet

**Comment by xepozz** [comment]
ValidatorCollector is in master now. Be aware that parameters naming [was changed a bit](https://github.com/yiisoft/yii-debug/blob/master/src/Collector/ValidatorCollector.php#L40). Also viewer was refactored.
